chore: adjust storage options for MapeoManager and MapeoProject
digidem/mapeo-core-next pull request #235
Opened 2023-08-29 21:15 UTC by achou11

Closes #226 

Tried my best to follow the checklist but there were some uncertainties, mostly around handling the `storage` opt in `MapeoProject`

2023-08-29 21:23 UTC, achou11 commented on src/mapeo-project.js
> +        : (name) => storage(path.join(INDEXER_STORAGE_FOLDER_NAME, name))
> If a path is passed, use a [default random-access-file storage function](https://github.com/digidem/mapeo-core-next/blob/main/src/mapeo-project.js#L74-L78)

>  Inside MapeoProject, the storage function will still need to be wrapped to separate index storage from core storage.

Made the guess that these points applied here, but could be mistaken

2023-08-29 21:23 UTC, achou11 commented on src/mapeo-project.js
> +   * @param {import('./core-manager/random-access-file-pool.js').RandomAccessFilePool} [opts.filePool] FilePool instance to use if opts.storage is a path
> Create a single instance of RandomAccessFilePool in MapeoManager and use that for all storages

is this aligned with what you described here? wasn't explicitly noted to create an opt for MapeoProject but seemed to make sense given the changes required by other points

2023-08-29 21:28 UTC, achou11 commented on src/mapeo-manager.js
> +          })
have a feeling that this shouldn't be a function that creates a new RAM instance each time a project is created. is the idea to share the ram instance across all projects too?

2023-08-30 07:46 UTC, gmaclennan commented
Not quite what I meant, sorry the issue wasn't clear. I pushed https://github.com/digidem/mapeo-core-next/pull/235/commits/28d4f8963366270fdab70cf2869f077f4c0ebf75 to show what I meant. I think this is done now, can you review?

2023-08-30 11:21 UTC, gmaclennan commented
Should merge and release https://github.com/digidem/multi-core-indexer/pull/17 before merging, so that we can update the snapshot and fix the storage locations

2023-08-30 11:28 UTC, gmaclennan requested changes
I made some changes and added a test to catch breaking changes to storage locations. There is a bug fix here for something unrelated (encoding project keys). There should be a failing test for that, in a separate PR.

2023-08-30 13:44 UTC, gmaclennan approved these changes

2023-08-30 14:01 UTC, achou11 commented
your changes lgtm! thanks for making the fixes - was hoping to do this to take something off your plate but ended up with you doing most of the work anyways 😄

2023-08-30 14:02 UTC, merged