Chore: expose icon data type
digidem/mapeo-core-next pull request #418
Opened 2023-12-13 17:52 UTC by tomasciccola

2023-12-13 18:48 UTC, achou11 requested changes
Can you elaborate on the reason for this? How and where would this be used?

Without any additional context, think it would make more sense to expose specific methods on the IconApi that use the dataType internally, as opposed to exposing the whole dataType.

2023-12-13 18:54 UTC, tomasciccola commented
> Can you elaborate on the reason for this? How and where would this be used?

Updated the PR description with more info

2023-12-13 19:05 UTC, achou11 commented
hm yeah i think given the context, it would be preferable to expose methods (maybe private symbol ones, depending on where this is being used)

2023-12-14 14:49 UTC, tomasciccola commented
I'm closing this PR since I messed stuff with a rebase and this is the least time consuming solution :|, new PR is #421

2023-12-14 14:50 UTC, closed without merging